[DropDownMenuContentSettings] 
TopList[]
TopList[]=folder
TopList[]=article_mainpage
TopList[]=blog
TopList[]=frontpage
TopList[]=forum_topic
TopList[]=proffolder
TopList[]=profgroup
TopList[]=classe
TopList[]=classgroup
TopList[]=forums
TopList[]=presentazione
TopList[]=folder_corsi
TopList[]=feedback_form
TopList[]=scatola_scuole
TopList[]=ticketsystem
TopListRestricted[]
TopListRestricted[]=folder
TopListRestricted[]=article_mainpage
TopListRestricted[]=frontpage
