[DropDownMenuContentSettings] 
TopList[]
TopList[]=folder
TopList[]=article_mainpage
TopList[]=blog
TopList[]=frontpage
TopList[]=forum_topic
TopList[]=forums
TopList[]=contatti
TopList[]=multicalendar
TopList[]=dmsfolder
TopList[]=progetto
TopList[]=event_calendar
TopList[]=feedback_form
TopListRestricted[]
TopListRestricted[]=folder
TopListRestricted[]=article_mainpage
TopListRestricted[]=frontpage
TopListRestricted[]=blog
TopListRestricted[]=dmsfolder
TopListRestricted[]=event_calendar
