{run-once}
{ezcss_require(array('javascript/fancybox.css'))}
{ezscript_require( array('classes/jquery.fancybox.js','classes/jquery.easing.js','init_ezimage.js'))}
{/run-once}
{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{*
Input:
 image_class - Which image alias to show, default is large
 css_class     - Optional css class to wrap around the <img> tag, the
                 class will be placed in a <div> tag.
 alignment     - How to align the image, use 'left', 'right' or false().
 link_to_image - boolean, if true the url_alias will be fetched and
                 used as link.
 href          - Optional string, if set it will create a <a> tag
                 around the image with href as the link.
 border_size   - Size of border around image, default is 0
 image_css_class -css img class
 zoom

*}

{if is_set($image_class)|not}
      {def $image_class=large}
{/if}        
{if is_set($css_class)|not}
    {def $css_class=false()}
{/if}
{if is_set($zoom)|not}
    {def $zoom=false()}
{/if}
{if is_set($image_css_class)|not}
    {def $image_css_class=false()}
{/if}
{if is_set($alignment)|not}
    {def $alignment=false()}
{/if}
{if is_set($link_to_image)|not}
    {def $link_to_image=false()}
{/if}
{if is_set($href)|not}
    {def $href=false()}
{/if}
{if is_set($link_to_image)|not}
    {def $link_to_image=false()}
{/if}
{if is_set($target)|not}
    {def $target=false()}
{/if}
{if is_set($hspace)|not}
    {def $hspace=false()}
{/if}
{if is_set($target)|not}
    {def $target=false()}
{/if}
{if is_set($border_size)|not}
    {def $border_size=0}
{/if}
{if is_set($border_style)|not}
    {def $border_style=''}
{/if}
{if is_set($margin_size)|not}
    {def $margin_size=''}
{/if}
{if is_set($alt_text)|not}
    {def $alt_text=''}
{/if}

{if is_set($title)|not}
    {def $title=''}
{/if}

{def    $image_content = $attribute.content}

{if $image_content.is_valid}

    {def $image        = $image_content[$image_class]
         $inline_style = ''}

    {if $link_to_image}
        {set $href = $image_content['original'].url|ezroot}
    {/if}
    {switch match=$alignment}
    {case match='left'}
        <div class="imageleft">
    {/case}
    {case match='right'}
        <div class="imageright">
    {/case}
    {case/}
    {/switch}

    {if $css_class}
        <div class="{$css_class|wash}">
    {/if}

    {if and( is_set( $image ), $image )}
        {if $alt_text|not}
            {if $image.text}
                {set $alt_text = $image.text}
            {else}
                {set $alt_text = $attribute.object.name}
            {/if}
        {/if}
        {if $title|not}
            {set $title = $alt_text}
        {/if}
        
        {if $margin_size|trim|ne('')}
            {set $inline_style = concat( $inline_style, 'margin: ', $margin_size, 'px;' )}
        {/if}
        
        <div class="image-wrapper">
        {if $href}<a href={$href}{if and( is_set( $link_class ), $link_class )} class="{$link_class}"{/if}{if and( is_set( $link_id ), $link_id )} id="{$link_id}"{/if}{if $target} target="{$target}"{/if}>{/if}
        <img class="{$image_css_class|wash}" src={$image.url|ezroot} width="{$image.width}" height="{$image.height}" {if $hspace}hspace="{$hspace}"{/if} style="{$inline_style}" alt="{$alt_text|wash(xhtml)}" title="{$title|wash(xhtml)}" />
             
        {if $href}</a>{/if}
        
       
        {if $zoom}
        <div class="zoom"><img src={'props/zoom.png'|ezimage()}/></div>
        {/if}
        </div>

    {/if}

    {if $css_class}
        </div>
    {/if}

    {switch match=$alignment}
    {case match='left'}
        </div>
    {/case}
    {case match='right'}
        </div>
    {/case}
    {case/}
    {/switch}
{/if}

{undef}
