{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{def $node=$version.temp_main_node}
{def  $content_object=$node.object
      $content_version=$node.contentobject_version_object
      $node_name=$node.name|wash}


<div class="object">
    <h1>{$node_name}</h1>
    <input type="hidden" name="TopLevelNode" value="{$content_object.main_node_id}" />

    {foreach $content_version.contentobject_attributes as $ContentObjectAttribute}
    <div class="block">
        <label>{$ContentObjectAttribute.contentclass_attribute.name|wash}</label>
        <p class="box">{attribute_view_gui attribute=$ContentObjectAttribute}</p>
    </div>
    {/foreach}

    <h3>{'Placed in'|i18n('design/standard/node/view')}</h3>
    {def $parent_node=''}
    {foreach $content_object.current.parent_nodes as $Parent}
        {set $parent_node=fetch('content','node',hash('node_id',$Parent.parent_node))}

        {foreach $parent_node.path as $Path}
            {node_view_gui view=text_linked content_node=$Path} /
        {/foreach}
        {node_view_gui view=text_linked content_node=$parent_node}<br/>
        {undef $parent_node}
    {/foreach}
</div>


{def $related_objects=$content_version.related_contentobject_array}

{foreach $related_objects as $ContentObject}
<div class="block">
    {content_view_gui view=text_linked content_object=$ContentObject}
</div>
{/foreach}
{undef $related_objects}


