[DropDownMenuContentSettings] 
TopList[]
TopList[]=folder
TopList[]=article_mainpage
TopList[]=blog
TopList[]=frontpage
TopList[]=forum_topic
TopList[]=profgroup
TopList[]=classgroup
TopList[]=ufficio
TopList[]=m2000_front
TopList[]=forums
TopList[]=dir_circolari
TopList[]=contatti
TopList[]=multicalendar
TopList[]=dipendenti
TopList[]=dmsfolder
TopList[]=link
TopList[]=progetto
TopList[]=event_calendar
TopListRestricted[]
TopListRestricted[]=folder
TopListRestricted[]=article_mainpage
TopListRestricted[]=frontpage
TopListRestricted[]=blog
TopListRestricted[]=progetto
